import test from 'node:test';import assert from 'node:assert/strict';
import {createRoom,joinRoom,act} from '../src/core/room.js';
import {parseSave,validateSave} from '../src/core/storage.js';
const host={id:'h',name:'형',token:'secret-must-never-broadcast'},guest={id:'g',name:'친구'};
function ready(){let r=createRoom(host,'테스트');r=joinRoom(r,guest);return act(r,'g',{type:'ready'});}
test('public host state excludes session credentials',()=>assert.equal(createRoom(host,'방').players[0].token,undefined));
test('duplicate nickname and ID, full lobby, host-only start, readiness',()=>{let r=createRoom(host,'방');assert.throws(()=>act(r,'h',{type:'start'}));assert.throws(()=>joinRoom(r,{id:'x',name:'형'}));assert.throws(()=>joinRoom(r,{id:'h',name:'다른이름'}));r=joinRoom(r,guest);assert.throws(()=>act(r,'g',{type:'start'}));assert.throws(()=>act(r,'h',{type:'start'}));r=act(r,'g',{type:'ready'});r=act(r,'h',{type:'start'});assert.equal(r.phase,'playing');assert.throws(()=>joinRoom(r,{id:'n',name:'새사람'}));let full=createRoom(host,'방');for(let i=0;i<7;i++)full=joinRoom(full,{id:String(i),name:'참가'+i});assert.throws(()=>joinRoom(full,{id:'9',name:'초과'}));});
test('chat limits and offline users rejected',()=>{let r=ready();r=act(r,'g',{type:'chat',text:'<img onerror=alert(1)>\n메모'});assert.equal(r.messages.at(-1).text,'<img onerror=alert(1)>\n메모');assert.throws(()=>act(r,'g',{type:'chat',text:'a'.repeat(401)}));r.players[1].online=false;assert.throws(()=>act(r,'g',{type:'roll'}));r=act(r,'h',{type:'remove',playerId:'g'});assert.equal(r.players.length,1);});
test('versioned save verifies rules and historical scores',()=>{let r=act(ready(),'h',{type:'start'});r=act(r,'h',{type:'roll'});r=act(r,'h',{type:'score',category:'choice'});const data={id:r.id,version:1,savedAt:Date.now(),room:r,tokens:{g:'123456789012345678901234567890'}};assert.deepEqual(parseSave(JSON.stringify(data)),data);let bad=structuredClone(data);bad.version=2;assert.throws(()=>validateSave(bad));bad=structuredClone(data);bad.room.game.scores.h.choice=999;assert.throws(()=>validateSave(bad));bad=structuredClone(data);bad.room.game.rules='yahtzee';assert.throws(()=>validateSave(bad));bad=structuredClone(data);bad.tokens={};assert.throws(()=>validateSave(bad));});
