import {categories,score,total,ranking} from '../games/yacht/scoring.js';
import {currentPlayer} from '../games/yacht/engine.js';
import {games,getGame} from '../games/registry.js';
import {bluffView,bluffRules} from '../games/bluff/ui.js';
export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(action,text,extra='')=>`<button data-action="${action}" ${extra}>${text}</button>`;
const letters=()=>`<div class="letters" aria-hidden="true"><span>◢</span>${'ABCDEFGHIJKLMN'.split('').map(l=>`<span>${l}</span>`).join('')}</div>`;
const tag=text=>`<span class="tag">${text}</span>`;
export function view(s){
 const r=s.room,host=r?.hostId===s.self.id,g=r?.game,gameId=r?.gameId||s.fields.gameId||'yacht',def=getGame(gameId);const turn=g&&r.players.find(p=>p.id===currentPlayer(g));
 return `<header class="titlebar"><div class="brand"><span class="sheet-icon" aria-hidden="true">▦</span><b>HIDE ON BG</b><span class="brand-divider">/</span><span>${esc(r?.title||'공유 통합 문서')}</span><span class="filetype">.${gameId}</span></div><div class="title-right">${r?esc(r.players.length)+'명 공동 작업':'개인 워크스페이스'}<span class="avatar">${esc(s.self.name?.slice(0,1)||'나')}</span></div></header>
 <nav class="ribbon-tabs" aria-label="메뉴">${button('home','파일',`class="${s.tab==='home'?'active':''}"`)}${button('game','홈',`class="${s.tab==='game'?'active':''}"`)}${button('saves','저장 문서',`class="${s.tab==='saves'?'active':''}"`)}${button('rules','도움말',`class="${s.tab==='rules'?'active':''}"`)}<span class="ribbon-caption">워크시트로 즐기는 보드게임</span></nav>
 <div class="toolbar"><div class="toolgroup">${button('save','▣ <span>저장</span>','aria-label="저장" title="저장" '+(!host?'disabled':''))}${button('export','↗ <span>내보내기</span>','aria-label="내보내기" title="내보내기" '+(!host?'disabled':''))}${button('import','↙ <span>불러오기</span>','aria-label="불러오기" title="불러오기" '+(r?'disabled':''))}<input type="file" id="import-file" accept="application/json,.json" hidden></div><div class="toolgroup"><span class="font-box">기본 서체 <b>⌄</b></span><span class="font-size">11</span><span class="toolbar-label">${esc(def.name)} · ${gameId==='bluff'?'Exact 1.0':'Classic 1.0'}</span></div><div class="toolgroup last">${r?.mode==='multi'?button('copy','⧉ 초대 코드'):tag(gameId==='bluff'?'비공개 주사위 · 2–6명':'12개 항목 · 3회 굴림')}${r?button('leave',host?'문서 닫기':'나가기'):''}</div></div>
 <div class="formula"><span class="cell-address">${g?String.fromCharCode(66+g.turn)+(g.round+3):'A1'}</span><span class="fx">ƒx</span><span>${g&&g.phase==='playing'?`${esc(turn.name)}님의 차례 · ${gameId==='bluff'?(g.stage==='result'?'공개 판정 확인':'선언 또는 BLUFF를 선택하세요'):g.rolls? '주사위를 보관하거나 점수 셀을 선택하세요':'주사위를 굴려 시작하세요'}`:r?.phase==='lobby'?'참가자 준비 상태를 확인한 뒤 Host가 시작합니다.':'= 함께할 사람과 오늘의 기록을 만들어 보세요'}</span></div>
 <div id="notice" class="notice ${s.error?'error':''}" role="status" aria-live="polite" ${!s.notice&&!s.error?'hidden':''}>${esc(s.error||s.notice)}${button('dismiss','닫기','aria-label="알림 닫기"')}</div>
 <main id="sheet" tabindex="-1">${letters()}${s.tab==='rules'?(gameId==='bluff'?bluffRules():rules()):s.tab==='saves'?saves(s):r&&s.tab!=='home'?workspace(s):home(s)}</main>
 <footer><nav class="sheet-tabs" aria-label="워크시트">${button('home','시작',`class="${s.tab==='home'?'selected':''}"`)}${button('game',gameId==='bluff'?'Bluff':'요트다이스',`class="${s.tab==='game'?'selected':''}"`)}${button('log','작업 기록',`class="${s.tab==='log'?'selected':''}" ${!r?'disabled':''}`)}${button('rules','규칙 안내',`class="${s.tab==='rules'?'selected':''}"`)}</nav><div class="statusbar"><span><i class="status-dot ${s.status.startsWith('연결됨')?'online':''}"></i>${esc(s.status)}</span><span>${esc(s.saveStatus||'준비')}<span class="desktop-only">　│　100%</span></span></div></footer>`;
}
function home(s){return `<div class="home-grid"><div class="row-numbers" aria-hidden="true">${Array.from({length:22},(_,i)=>`<span>${i+1}</span>`).join('')}</div><section class="start-sheet"><div class="eyebrow">WORKSPACE / 01</div><h1>오늘의 기록을<br>함께 채워볼까요.</h1><p class="intro">익숙한 워크시트, 새로운 한 판.<br>혼자 연습하거나 동료와 같은 문서를 열어보세요.</p><div class="setup-table"><div class="table-heading"><span>A</span><span>B · 입력 값</span></div><label><span>01　닉네임</span><input id="nickname" data-field="nickname" maxlength="16" autocomplete="nickname" placeholder="어떤 이름으로 참여할까요?" value="${esc(s.fields.nickname)}"></label><label><span>02　문서 이름</span><input id="roomname" data-field="roomname" maxlength="40" value="${esc(s.fields.roomname)}"></label><div class="setup-row"><span>03　워크시트</span><select id="game-select" data-field="gameId" aria-label="게임 선택">${Object.values(games).map(g=>`<option value="${g.id}" ${(s.fields.gameId||'yacht')===g.id?'selected':''}>${g.name} · ${g.minPlayers}–${g.maxPlayers}명</option>`).join('')}</select></div></div><div class="start-actions">${button('solo','컴퓨터와 시작 <span>↗</span>','class="primary" '+(s.busy?'disabled':''))}${button('host','공유 문서 만들기 <span>＋</span>',s.busy?'disabled':'')}</div><div class="join-block"><label for="invite">초대받은 문서 열기</label><div><input id="invite" data-field="invite" placeholder="초대 코드 10자리" maxlength="20" autocapitalize="characters" value="${esc(s.fields.invite)}">${button('join','참가하기',s.busy?'disabled':'')}</div></div>${s.lastJoin?`<div class="resume-guest">마지막 참여 문서 · ${esc(s.lastJoin.code)} ${button('rejoin','재접속')}</div>`:''}${!s.room&&(s.status.startsWith('연결')||s.status.startsWith('Host'))?button('cancel','연결 취소',s.busy?'disabled':''):''}<div class="home-foot">설치 없이 브라우저에서 · 자동 저장 · 모바일 지원</div></section><aside class="home-aside"><div class="note-number">${s.fields.gameId==='bluff'?'02 / BLUFF':'01 / YACHT DICE'}</div><h2>작은 선택이<br>큰 기록으로.</h2><div class="sample-dice" aria-hidden="true"><span>2</span><span class="held">5</span><span class="held">5</span><span>3</span><span class="held">5</span></div><p>${s.fields.gameId==='bluff'?'내 주사위만 보고 전체를 추리하세요.<br>선언을 높이거나 BLUFF로 도전하세요.':'다섯 개의 주사위, 세 번의 기회.<br>남길 숫자를 선택하고 가장 좋은 항목에 기록하세요.'}</p><dl><div><dt>진행 방식</dt><dd>${s.fields.gameId==='bluff'?'선언 · 도전 · 공개 판정':'차례대로 점수 기록'}</dd></div><div><dt>참여 인원</dt><dd>혼자 + AI / 친구 2–${s.fields.gameId==='bluff'?6:8}명</dd></div><div><dt>저장 방식</dt><dd>이 브라우저에 자동 저장</dd></div></dl><div class="tip"><b>처음이라면</b><p>컴퓨터와 한 판을 시작해 보세요.<br>${s.fields.gameId==='bluff'?'더 높은 선언만 목록에 표시돼요.':'선택 가능한 셀에 예상 점수가 표시돼요.'}</p></div>${button('saves','저장한 문서 이어하기 →','class="text-link"')}</aside></div>`;}
function workspace(s){const r=s.room;if(s.tab==='log')return `<section class="document"><div class="eyebrow">WORKSHEET / LOG</div><h1>작업 기록</h1><table class="log-table"><thead><tr><th>시각</th><th>작성자</th><th>내용</th></tr></thead><tbody>${r.messages.map(m=>`<tr><td>${new Date(m.time).toLocaleTimeString('ko-KR')}</td><td>${esc(m.sender)}</td><td>${esc(m.text)}</td></tr>`).join('')}</tbody></table></section>`;
 return `<div class="workspace"><section class="work-area">${r.phase==='lobby'?lobby(s):game(s)}</section>${comments(s)}</div>`;}
function lobby(s){const r=s.room,host=r.hostId===s.self.id;return `<div class="doc-heading"><div><div class="eyebrow">공유 문서 / 대기실</div><h1>${esc(r.title)}</h1></div>${tag(`${r.players.length} / ${getGame(r.gameId).maxPlayers}명`)}</div><label class="game-picker" for="lobby-game">게임 선택 <select id="lobby-game" data-field="lobbyGame" ${!host?'disabled':''}>${Object.values(games).map(g=>`<option value="${g.id}" ${(s.fields.lobbyGame||r.gameId)===g.id?'selected':''}>${g.name} · ${g.minPlayers}–${g.maxPlayers}명</option>`).join('')}</select>${host?button('selectGame','게임 적용'):''}</label><div class="invite-box"><div><small>초대 코드</small><strong id="room-code">${esc(r.code)}</strong></div>${button('copy','코드 복사')}</div><p class="muted">친구에게 코드를 전달하세요. 모두 준비하면 Host가 게임을 시작할 수 있어요.</p><table class="players-table"><thead><tr><th>행</th><th>참가자</th><th>역할</th><th>상태</th></tr></thead><tbody>${r.players.map((p,i)=>`<tr><td>${i+1}</td><td><span class="player-dot">${esc(p.name.slice(0,1))}</span>${esc(p.name)}${p.id===s.self.id?' <small>(나)</small>':''}</td><td>${p.id===r.hostId?'Host':'참가자'}</td><td>${!p.online?'연결 끊김'+(host?button('remove','정리',`data-player="${esc(p.id)}"`):''):p.ready?'✓ 준비 완료':'준비 중'}</td></tr>`).join('')}</tbody></table><div class="lobby-actions">${host?button('start','게임 시작','class="primary" '+(r.players.length<2||r.players.some(p=>!p.ready||!p.online)?'disabled':'')):button('ready',r.players.find(p=>p.id===s.self.id)?.ready?'준비 취소':'준비 완료','class="primary"')}<span class="muted">${host?'2명 이상 · 모든 참가자 준비 필요':'준비 완료 후 Host의 시작을 기다려주세요.'}</span></div><div class="tip"><b>연결과 저장</b><p>Host가 문서를 열어두면 게임이 진행돼요. 연결이 끊기면 차례를 유지하며, Host는 저장 문서에서 이어갈 수 있어요. 게임 시작 후에는 기존 참가자만 재접속할 수 있어요.</p></div>`;}
function game(s){if(s.room.gameId==='bluff')return bluffView(s,{esc,button,tag});const r=s.room,g=r.game,turn=r.players.find(p=>p.id===currentPlayer(g)),mine=turn.id===s.self.id&&g.phase==='playing'&&(r.mode==='solo'||s.status.startsWith('연결됨')),host=r.hostId===s.self.id;
 return `<div class="doc-heading"><div><div class="eyebrow">WORKSHEET / YACHT DICE</div><h1>요트다이스 <span class="subtitle">점수 기록표</span></h1></div>${tag(g.phase==='finished'?'기록 완료':`${g.round} / 12 라운드`)}</div>
 ${g.phase==='finished'?`<div class="result"><span>최종 결과</span><h2>${ranking(r.players,g).filter(p=>p.rank===1).map(p=>esc(p.name)).join(' · ')} ${ranking(r.players,g).filter(p=>p.rank===1).length===1?'1위':'공동 1위'}</h2><div class="result-list">${ranking(r.players,g).map(p=>`<span>${p.forfeited?'기권':p.rank+'위'}　${esc(p.name)} <b>${p.total}</b></span>`).join('')}</div>${host?button('rematch','새 문서에서 다시 하기'):''}</div>`:`<div class="turn-strip"><span class="turn-name">${mine?'내 차례':esc(turn.name)+'님의 차례'}</span><span>${!turn.online?'재접속을 기다리고 있어요':mine?(g.rolls?'보관할 주사위를 선택하거나 아래 점수 셀에 기록하세요.':'주사위를 굴려주세요.'):'상대의 기록을 기다리고 있어요.'}</span></div><div class="dice-panel"><div class="dice-row">${g.dice.map((v,i)=>`<button class="die ${g.held[i]?'held':''}" data-action="hold" data-index="${i}" aria-label="주사위 ${i+1}, ${g.rolls?v:'미굴림'}, ${g.held[i]?'보관됨':'보관 안 됨'}" aria-pressed="${g.held[i]}" ${!mine||!g.rolls||g.rolls>=3?'disabled':''}><small>${String.fromCharCode(66+i)}${g.round+3}</small><b>${g.rolls?v:'–'}</b><span>${g.held[i]?'✓ 보관':'선택'}</span></button>`).join('')}</div><div class="roll-box">${button('roll',g.rolls?'다시 굴리기':'주사위 굴리기',`class="primary" ${!mine||g.rolls>=3||(g.rolls&&g.held.every(Boolean))?'disabled':''}`)}<small>${g.rolls} / 3회 사용 <span class="desktop-only">· Space</span></small></div></div>`}
 <div class="score-scroll" role="region" aria-label="플레이어 점수표" tabindex="0"><table class="score-table"><thead><tr class="column-letters"><th></th><th>A</th>${r.players.map((_,i)=>`<th>${String.fromCharCode(66+i)}</th>`).join('')}</tr><tr><th>#</th><th>평가 항목 <small>Classic Yacht</small></th>${r.players.map(p=>`<th class="${p.id===turn.id&&g.phase==='playing'?'active-col':''}">${esc(p.name)}${p.id===s.self.id?'<small>나</small>':''}<small>${g.forfeited.includes(p.id)?'기권':p.bot?'컴퓨터':p.online?'접속 중':'연결 끊김'}</small></th>`).join('')}</tr></thead><tbody>${categories.map((c,i)=>`<tr><td class="row-index">${i+1}</td><th scope="row">${c.label}<small>${c.hint}</small></th>${r.players.map(p=>{const value=g.scores[p.id][c.id],can=mine&&p.id===s.self.id&&value===undefined&&g.rolls>0;return `<td class="${p.id===turn.id&&g.phase==='playing'?'active-col':''} ${value===undefined?'unfilled':''}">${can?button('score',`${score(c.id,g.dice)}<small>기록</small>`,`data-category="${c.id}" aria-label="${c.label} ${score(c.id,g.dice)}점 기록" class="score-choice"`):value===undefined?'—':value}</td>`;}).join('')}</tr>`).join('')}<tr class="total-row"><td>Σ</td><th>합계<small>상단 보너스 없음</small></th>${r.players.map(p=>`<td>${total(g.scores[p.id])}</td>`).join('')}</tr></tbody></table></div>
 <div class="table-foot">${mine?'예상 점수가 표시된 셀을 선택하면 이번 차례가 끝납니다.':'각자 12개 항목을 기록하면 종료됩니다.'}<span>보관: 숫자키 1–5 · 굴리기: Space</span></div>${host&&g.phase==='playing'?r.players.filter(p=>!p.online&&!g.forfeited.includes(p.id)).map(p=>`<div class="offline-row">${esc(p.name)}님 연결 끊김 ${button('forfeit','기권 처리',`data-player="${esc(p.id)}"`)}</div>`).join(''):''}`;
}
function comments(s){return `<aside class="comments"><div class="comments-heading"><h2>메모</h2><span>공동 작업</span></div><p class="comments-caption">이 문서의 대화와 변경 사항</p><div class="messages" role="log" aria-label="메모 대화">${s.room.messages.map(m=>`<div class="message ${m.system?'system':''}"><div><b>${esc(m.sender)}</b><time>${new Date(m.time).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}</time></div><p>${esc(m.text)}</p></div>`).join('')||'<p class="empty-note">첫 메모를 남겨보세요.</p>'}</div><form id="chat-form"><label class="sr-only" for="chat">메모 작성</label><textarea id="chat" data-field="chat" maxlength="400" rows="2" placeholder="메모 작성…">${esc(s.fields.chat)}</textarea><div><small>Enter 전송 · Shift+Enter 줄바꿈</small><button type="submit">게시</button></div></form></aside>`;}
function saves(s){return `<section class="document"><div class="eyebrow">FILE / SAVED WORKBOOKS</div><h1>저장 문서</h1><p class="muted">이 브라우저의 Host 기록이에요. 다른 기기로 옮기려면 JSON으로 내보내세요.</p>${s.saves.length?`<div class="save-list">${s.saves.map(v=>`<article><span class="save-icon">▦</span><div><h2>${esc(v.room.title)}</h2><p>${new Date(v.savedAt).toLocaleString('ko-KR')} · ${v.room.players.length}명 · ${v.room.phase==='finished'?'완료':v.room.game?(v.room.game.round+'라운드'):'대기실'}</p></div><div>${button('restore','열기',`data-id="${esc(v.id)}" ${s.busy||s.room?'disabled':''}`)}${button('exportSaved','내보내기',`data-id="${esc(v.id)}"`)}${button('delete','삭제',`data-id="${esc(v.id)}"`)}</div></article>`).join('')}</div>`:'<div class="empty-state">저장된 문서가 없어요. 게임을 시작하면 자동으로 저장돼요.</div>'}${button('import','JSON 파일 불러오기',s.room?'disabled':'')}</section>`;}
function rules(){return `<section class="document rules"><div class="eyebrow">REFERENCE / CLASSIC YACHT V1</div><h1>요트다이스 사용 안내</h1><p>주사위 5개를 굴려 12개 항목에 한 번씩 기록해요. 최종 합계가 가장 높으면 승리하고, 같은 점수는 공동 순위예요.</p><ol><li><b>굴리기</b> — 내 차례에 최대 3회. 첫 굴림은 5개 모두 굴려요.</li><li><b>보관하기</b> — 남길 주사위를 선택하세요. 다음 굴림 전에 해제할 수도 있어요.</li><li><b>기록하기</b> — 1회 이상 굴린 뒤 언제든 빈 점수 셀 하나에 기록해요. 조건을 만족하지 않으면 0점이에요.</li></ol><table class="rules-table"><thead><tr><th>항목</th><th>조건 및 점수</th></tr></thead><tbody>${categories.map(c=>`<tr><td>${c.label}</td><td>${c.hint}${['little','big'].includes(c.id)?' · 30점':c.id==='yacht'?' · 50점':''}</td></tr>`).join('')}</tbody></table><p><b>고전 Yacht 규칙:</b> 상단 보너스, 3-of-a-kind, 조커, 추가 Yacht 보너스는 없어요. 같은 눈 5개는 풀하우스가 아니며 포카드에는 그중 4개만 합산해요. Yahtzee 및 4연속 스트레이트 변형과 구분해요.</p><h2>연결이 끊겼나요?</h2><p>참가자는 같은 브라우저에서 ‘마지막 참여 문서 → 재접속’을 이용하세요. Host는 저장 문서에서 열면 같은 초대 코드로 복구돼요. Host가 없으면 게임은 멈춰요. 돌아오지 않는 참가자는 Host가 기권 처리할 수 있어요.</p><h2>저장과 개인정보</h2><p>자동 저장은 Host 브라우저에 보관돼요. 브라우저 데이터 삭제·시크릿 모드 종료 시 사라질 수 있으니 중요한 기록은 내보내세요. JSON에는 재접속 인증정보와 메모가 포함되므로 개인적으로 보관하세요.</p><h2>키보드와 모바일</h2><p>Tab으로 이동, Enter로 선택, Space로 굴리기, 숫자키 1–5로 보관해요. 모바일에서는 점수표를 옆으로 밀어 다른 참가자의 열을 확인하세요.</p><p class="muted">규칙 출처: Family Games Treasurehouse, 25 Family Dice Games (2009)의 Yacht. 구현은 classic-yacht-v1로 고정. <a href="https://www.party2geaux.com/wp-content/uploads/2017/12/dice-rules.pdf" target="_blank" rel="noopener noreferrer">출처 보기 ↗</a></p></section>`;}
