import {availableBids,bidLabel,faceLabel} from './rules.js';
export function bluffView(s,{esc,button,tag}){
 const r=s.room,g=r.game,host=r.hostId===s.self.id,turn=r.players.find(p=>p.id===g.order[g.turn]);
 const mine=g.phase==='playing'&&g.stage==='bid'&&turn.id===s.self.id&&(r.mode==='solo'||s.status.startsWith('연결됨'));
 const own=g.ownDice||g.dice?.[s.self.id]||[],options=availableBids(g.bid),selected=options.find(b=>`${b.count}:${b.face}`===s.fields.bluffBid)||options[0];
 const playerName=id=>esc(r.players.find(p=>p.id===id)?.name||'—');
 return `<div class="bluff-sheet" data-round="${g.round}" data-stage="${g.stage}" data-turn="${esc(turn.id)}"><div class="doc-heading"><div><div class="eyebrow">WORKSHEET / BLUFF</div><h1>Bluff <span class="subtitle">선언 검토표</span></h1></div>${tag(`${g.round}라운드`)}</div>
 ${g.phase==='finished'?`<div class="result"><span>최종 결과</span><h2>${playerName(g.winner)} 승리</h2>${host?button('rematch','새 문서에서 다시 하기'):''}</div>`:`<div class="turn-strip"><b class="turn-name">${g.stage==='result'?'공개 판정':mine?'내 차례':playerName(turn.id)+'님의 차례'}</b><span>${g.stage==='result'?'판정을 확인한 뒤 Host가 다음 라운드를 엽니다.':!turn.online?'재접속을 기다립니다.':mine?'더 높은 선언을 선택하거나 BLUFF로 도전하세요.':'상대의 선언을 기다립니다.'}</span></div>`}
 <div class="invite-box"><div><small>현재 선언 · ${g.bid?playerName(g.bid.player):'—'}</small><strong class="bluff-bid">${bidLabel(g.bid)}</strong></div><span>전체 ${Object.values(g.counts).reduce((a,n)=>a+n,0)}개 남음</span></div>
 ${g.stage==='bid'?`<h2 class="bluff-label">내 주사위 <small>나에게만 표시</small></h2><div class="dice-panel"><div class="dice-row bluff-dice">${own.map((v,i)=>`<div class="die" aria-label="내 주사위 ${i+1}: ${faceLabel(v)}"><small>${String.fromCharCode(66+i)}${g.round}</small><b>${faceLabel(v)}</b><span>비공개</span></div>`).join('')||'<p>탈락 · 공개 정보로 관전 중</p>'}</div></div><div class="bluff-controls"><label for="bluff-bid">다음 선언<select id="bluff-bid" data-field="bluffBid" ${!mine?'disabled':''}>${options.map(b=>`<option value="${b.count}:${b.face}" ${b===selected?'selected':''}>${bidLabel(b)}</option>`).join('')}</select></label>${button('bluffBid','선언 기록',`class="primary" ${!mine||!options.length?'disabled':''}`)}${button('challenge','BLUFF · 도전',!mine||!g.bid?'disabled':'')}</div><p class="muted">숫자 선언에는 ★를 포함하고, ★ 선언에는 ★만 셉니다. 목록은 원작 보드 순서로 정렬됩니다.</p>`:''}
 ${g.result&&g.stage==='result'?`<div class="bluff-verdict"><h2>${g.result.exact?'Exact · 정확한 선언':'BLUFF 판정'}</h2><p>${playerName(g.result.caller)}님의 도전 · ${bidLabel(g.result.bid)} / 실제 <b>${g.result.actual}개</b></p><p>${Object.entries(g.result.losses).filter(([,n])=>n).map(([id,n])=>`${playerName(id)} −${n}개`).join(' · ')}</p></div>`:''}
 <table class="players-table bluff-players"><thead><tr><th>참가자</th><th>남은 수</th><th>주사위 / 상태</th></tr></thead><tbody>${r.players.map(p=>`<tr class="${p.id===turn.id&&g.stage==='bid'?'active-col':''}" data-player="${esc(p.id)}"><td>${playerName(p.id)}${p.id===s.self.id?' (나)':''}${p.id===r.hostId?' · Host':''}</td><td class="bluff-count">${g.counts[p.id]}</td><td>${g.stage==='result'&&g.result?`<span class="revealed-dice">${g.result.dice[p.id].map(faceLabel).join(' · ')||'—'}</span><small>판정 전 주사위</small>`:g.counts[p.id]===0?'—':p.id===s.self.id?'내 데이터':`${g.counts[p.id]}개 비공개`}<small>${g.forfeited.includes(p.id)?'기권':g.counts[p.id]===0?'탈락':!p.online?'연결 끊김':p.id===turn.id&&g.stage==='bid'?'▶ 현재 차례':'접속 중'}</small></td></tr>`).join('')}</tbody></table>
 ${g.phase==='playing'&&g.stage==='result'?(host?button('nextRound','다음 라운드 · 다시 굴리기','class="primary"'):'<p class="muted">Host의 다음 라운드 시작을 기다립니다.</p>'):''}
 ${host&&g.phase==='playing'?r.players.filter(p=>!p.online&&g.counts[p.id]>0).map(p=>`<div class="offline-row">${playerName(p.id)}님 연결 끊김 ${button('forfeit','기권 처리',`data-player="${esc(p.id)}"`)}</div>`).join(''):''}</div>`;
}
export function bluffRules(){return `<section class="document rules"><div class="eyebrow">REFERENCE / BLUFF EXACT V1</div><h1>Bluff 사용 안내</h1><p>2~6명, 각자 주사위 5개로 시작합니다. 컴퓨터와 둘이 연습할 수도 있습니다. 주사위는 1~5와 ★이며, 마지막까지 주사위를 가진 한 명이 승리합니다.</p><ol><li>내 주사위만 보고 전체에 특정 눈이 몇 개 이상인지 선언합니다. 일반 숫자에는 ★가 조커로 포함되고 ★ 선언에는 ★만 포함됩니다.</li><li>다음 사람은 더 높은 선언 또는 BLUFF를 선택합니다. 보드 순서는 숫자 1개 → ★ 1개 → 숫자 2개 → 숫자 3개 → ★ 2개 → 숫자 4개 … 입니다. 같은 숫자 개수에서는 눈을 올립니다. 숫자는 20개, ★는 10개가 마지막 칸입니다.</li><li>도전하면 모두 공개합니다. 실제 개수가 적으면 선언자, 많으면 도전자가 차이만큼 주사위를 잃습니다. Exact이면 선언자 외 모두 1개씩 잃으며 마지막 주사위도 잃습니다.</li><li>판정에서 이긴 사람이 다음 라운드를 시작합니다. Host가 ‘다음 라운드’를 누르면 남은 주사위를 새로 굴립니다. 첫 시작은 별도의 5개 굴림 합계(★=0)가 가장 큰 사람이며 동점은 다시 굴립니다.</li></ol><h2>연결과 저장</h2><p>연결이 잠시 끊기면 차례를 유지합니다. 같은 브라우저에서 재접속하세요. Host는 기존 저장 문서를 열어 복구합니다. 기권 시 진행 중 선언을 취소하고 남은 참가자의 주사위를 다시 굴립니다. 탈락자는 관전·메모를 계속 사용할 수 있습니다.</p><h2>비공개 정보</h2><p>참가자에게는 자기 주사위만 전송합니다. 공개 판정과 이전 라운드 기록은 모두에게 보입니다. Host는 판정을 담당하므로 전체 데이터와 저장 파일을 갖습니다. 믿을 수 있는 친구가 Host를 맡고, 저장 JSON은 공유하지 마세요.</p><p class="muted">Richard Borg / Ravensburger 원작 기본 규칙. 도중 재굴림 변형과 온라인 Exact 보호 변형은 사용하지 않습니다. <a href="https://m.brettspielwelt.de/pdf/Bluff.pdf" target="_blank" rel="noopener noreferrer">원작 규칙서 ↗</a></p></section>`;}
