import {HORSES,EFFECTS,cardById} from './rules.js';
export function darkhorseView(s,{esc,button,tag}){
 const r=s.room,g=r.game,host=r.hostId===s.self.id,turn=g.order[g.turn],name=id=>esc(r.players.find(p=>p.id===id)?.name||'—');
 const mine=g.phase==='playing'&&turn===s.self.id&&(r.mode==='solo'||s.status.startsWith('연결됨'));
 const own=g.ownHand||g.hands[s.self.id]||[],counts=g.handCounts||Object.fromEntries(g.order.map(id=>[id,g.hands[id].length]));
 const selection=s.fields.darkSelection,selected=selection?.key===`${r.id}:${g.step}`&&own.includes(selection.card)?selection:null,card=selected&&cardById(selected.card);
 const targets=card?.kind==='swap'&&selected.horse?HORSES.filter(h=>h!==selected.horse):HORSES;
 return `<div class="darkhorse-sheet" data-step="${g.step}" data-stage="${g.stage}" data-turn="${esc(turn)}"><div class="doc-heading"><div><div class="eyebrow">WORKSHEET / DARK HORSE · RANK VARIANT</div><h1>다크호스 순위전</h1></div>${tag(g.stage==='placement'?'말 배치':g.phase==='finished'?'기록 완료':`남은 카드 ${Object.values(counts).reduce((a,n)=>a+n,0)}장`)}</div>
 <p class="muted">베팅 없는 자체 변형 · 공개된 내 담당 말을 가장 앞에 두세요.</p>
 ${g.phase==='finished'?`<div class="result"><span>최종 결과</span><h2>${name(g.winner)} 승리</h2><div class="result-list">${g.ranking.map(p=>`<span>${p.rank}위　${name(p.id)} · ${g.owners[p.id]}번 말 ${p.position===null?'미배치':p.position+'위'}</span>`).join('')}</div>${host?button('rematch','새 문서에서 다시 하기'):''}</div>`:`<div class="turn-strip"><b class="turn-name">${mine?'내 차례':name(turn)+'님의 차례'}</b><span>${!r.players.find(p=>p.id===turn).online?'재접속을 기다립니다.':g.stage==='placement'?'아직 배치하지 않은 말을 선택하면 다음 순위 칸에 놓입니다.':mine?'손패 한 장을 선택한 뒤 적용할 말을 선택하세요.':'상대가 카드를 사용하는 동안 기다려주세요.'}</span></div>`}
 <h2>순위 기록 · 1위 → 7위</h2><table class="players-table darkhorse-order"><thead><tr><th>순위</th><th>말</th><th>담당자 / 표시</th></tr></thead><tbody>${Array.from({length:7},(_,i)=>{const h=g.horseOrder[i],owner=g.order.find(id=>g.owners[id]===h);return `<tr data-horse="${h||''}"><td>${i+1}</td><td>${h?`${h}번`:'—'}</td><td>${owner?name(owner)+(owner===s.self.id?' (나)':''):'—'}${h&&h===g.darkHorse?' · ◆ 다크호스':''}</td></tr>`;}).join('')}</tbody></table>
 ${g.stage==='placement'?`<div class="darkhorse-controls" aria-label="말 배치">${HORSES.filter(h=>!g.horseOrder.includes(h)).map(h=>button('darkPlace',`${h}번 배치`,`data-horse="${h}" ${!mine?'disabled':''}`)).join('')}</div>`:''}
 ${g.stage==='cards'?`<h2>내 액션 카드 <small>나에게만 표시 · 담당 ${g.owners[s.self.id]}번</small></h2><div class="darkhorse-hand">${own.map(id=>button('darkSelect',esc(cardById(id).label),`data-card="${id}" aria-pressed="${selected?.card===id}" ${!mine?'disabled':''}`)).join('')||'<p class="muted">남은 손패가 없습니다.</p>'}</div>${mine&&card?`<div class="darkhorse-targets"><p>${esc(card.label)} · ${card.kind==='swap'&&selected.horse?`${selected.horse}번과 교환할 다른 말`:'적용할 말'}을 선택하세요. 선택 즉시 적용됩니다.</p><div class="darkhorse-controls">${targets.map(h=>button('darkTarget',`${h}번`,`data-horse="${h}"`)).join('')}</div>${selected.horse?button('darkSelect','선택 취소',`data-card="${selected.card}"`):''}</div>`:''}`:''}
 <p class="darkhorse-last" aria-live="polite">직전 작업: ${g.lastAction?name(g.lastAction.actor)+' · '+esc(g.lastAction.text):'—'}</p>
 <table class="players-table darkhorse-players"><thead><tr><th>참가자</th><th>담당 말</th><th>손패</th><th>상태</th></tr></thead><tbody>${r.players.map(p=>`<tr data-player="${esc(p.id)}"><td>${name(p.id)}${p.id===s.self.id?' (나)':''}${p.id===r.hostId?' · Host':''}</td><td>${g.owners[p.id]}번</td><td>${counts[p.id]}장${p.id===s.self.id?'':' · 비공개'}</td><td>${g.forfeited.includes(p.id)?'기권':!p.online?'연결 끊김':g.phase==='playing'&&turn===p.id?'▶ 현재 차례':'대기'}</td></tr>`).join('')}</tbody></table>
 ${host&&g.phase==='playing'?r.players.filter(p=>!p.online&&!g.forfeited.includes(p.id)).map(p=>`<div class="offline-row">${name(p.id)}님 연결 끊김 ${button('forfeit','기권 처리',`data-player="${esc(p.id)}"`)}</div>`).join(''):''}</div>`;
}
export function darkhorseRules(){return `<section class="document rules"><div class="eyebrow">REFERENCE / DARKHORSE RANK V1</div><h1>다크호스 순위전 · 자체 변형</h1><p>사용자가 선택한 베팅 없는 순위 조작 게임입니다. 이주화의 2014년 원작 Dark Horse나 Minuscule의 공식 규칙을 재현하지 않습니다. 목표·베팅 카드, 토큰, +5/−3 보너스는 사용하지 않습니다.</p><ol><li>2~6명. 각자 서로 다른 담당 말 1마리를 공개 배정받고, 이동·교환 카드 5장을 비공개로 받습니다. 7마리 중 담당자가 없는 말도 이동할 수 있습니다. 6종류 카드가 각각 5장인 30장 덱에서 배분하며 남은 덱은 사용하지 않습니다.</li><li>무작위 시작 참가자부터 순서대로 아직 놓이지 않은 말 하나를 1위부터 7위까지 배치합니다. 마지막 배치된 말에 ◆ 다크호스를 표시합니다. 표시는 기록용이며 별도 점수 효과가 없습니다.</li><li>마지막 배치자의 다음 참가자부터 손패를 한 장씩 사용합니다. 카드를 선택한 후 적용할 말을 선택하세요. 두 말 교환은 서로 다른 두 말을 선택합니다.</li><li>순위 경계를 넘는 이동은 1위 또는 7위에서 멈춥니다. 연속 두 말은 선택한 말과 바로 뒤의 말을 묶어 순서를 유지한 채 앞으로 2칸 옮깁니다. 선택한 말이 마지막이면 그 말만 옮깁니다. 순위가 바뀌지 않아도 카드는 소비됩니다.</li><li>모든 참가자의 손패가 소진되면 종료합니다. 기권하지 않은 참가자의 담당 말 중 가장 앞에 있는 말의 담당자가 승리합니다. 하나의 말에 담당자가 중복되지 않으므로 공동 순위는 발생하지 않습니다.</li></ol><table class="rules-table"><thead><tr><th>카드</th><th>장수</th></tr></thead><tbody>${Object.values(EFFECTS).map(c=>`<tr><td>${c.label}</td><td>각 5장</td></tr>`).join('')}</tbody></table><h2>저장 · 재접속 · 기권</h2><p>기존 문서의 저장, 초대 코드, 메모 기능을 사용합니다. 연결이 끊겨도 게임을 초기화하지 않고 기다립니다. Host는 저장 문서를 열어 복구하며, 참가자는 같은 브라우저에서 재접속합니다. 기권자의 남은 카드는 공개하지 않고 폐기합니다. 담당 말은 남지만 승리 대상에서 제외됩니다. 한 명만 남으면 즉시 승리합니다.</p><h2>비공개 정보와 조작</h2><p>다른 참가자에게는 자신의 손패만 전송하고, 사용된 카드만 공개합니다. Host와 Host 저장 파일에는 전체 손패가 있으므로 저장 JSON은 공유하지 마세요. Tab과 Enter 또는 터치로 모든 선택을 할 수 있습니다. 컴퓨터 역시 자기 손패와 공개된 순위만 보고 행동합니다.</p></section>`;}
